name: 'Build Windows'
description: 'A Docker container to build Windows DLLs'
inputs:
  go-version:
    description: 'Version of Go to use'
    required: true
runs:
  using: composite
  steps:
    - name: Build image
      shell: bash
      run: |
        docker build --build-arg GO_VERSION="${{ inputs.go-version }}" -t remote-math-interface-windows-build:latest "${{ github.action_path }}"

    - name: Run image
      shell: bash
      run: |
        docker run --rm remote-math-interface-windows-build:latest
